---
name: ci

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 10
          cache: npm
      - run: |
          npm install
          node_modules/.bin/gulp lint
  bundle-stable:
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 10
          cache: npm
      - run: |
          npm install
          node_modules/.bin/gulp bundle
      - uses: softprops/action-gh-release@v1
        with:
          files: |
            README.md
            build/ui-bundle.zip
  bundle-dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 10
          cache: npm
      - run: |
          npm install
          node_modules/.bin/gulp bundle
      - uses: softprops/action-gh-release@v1
        with:
          tag_name: dev
          prerelease: true
          files: |
            README.md
            build/ui-bundle.zip
...
